version: "1.0"

services:
    eecone_ui:
        tty: true
        image: eecone:latest
        container_name: eecone_ui_app
        restart: always
        entrypoint: /bin/bash
        command: -c "streamlit run main.py"
        environment:
            - PYTHONPATH=/app
            - debug_mode=false
            - TZ=Europe/Athens
        volumes:
            - "D:/eecone/app:/app"
        working_dir: "/app/eecone_ui"
        ports:
            - "12460:8501"
        deploy:
            resources:
                limits:
                    memory: 1g